# Jekyll Resume Theme

# Site settings
title: nilq's portfolio
email: i.am@nilq.dk
description: my name is niels, born in 2002. please give me money
baseurl: ""
url: "http://nilq.dk"
name: nilq
job: wannabe programmer
location: copenhagen, denmark
languages: rust, moonscript, java, python, javascript, lua, ruby, crystal, html, css, c++ and many unknown languages ...
twitter_username: thenilq
github_username:  nilq
email_address: i.am@nilq.dk

# Build settings
markdown: kramdown
